# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 73bbc460bb2fd026f0663c6d0477773dac2324c009d6bfbea534e197162b9a20b0b3d36c0c2058f38fe18595361540a8ae8568d132227fcb41683d75def5012b

test:
  secret_key_base: ab32936fd08e06c922e4ff5d8f2686bfe5fba679ee56ef2684e9ab43c67b6396e9d714204178c334f77acf49a4c35381f3fecb5eaedcba3de14220f51ccc8474

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
